### ISSUE TITLE
DNAD

### ISSUE THREAD

**Issue by stumarcus314** [jacobwilliams/slsqp#11]
As an alternative to finite-differences, dual numbers can be used to compute the Jacobians for SLSQP without error (up to machine precision).

https://www.sciencedirect.com/science/article/pii/S0010465513000027
https://github.com/joddlehod/dnad/blob/master/dnad.F90

**Comment by jacobwilliams** [comment]
Yes indeed. I wouldn't want to include that in this code though. If the user wants an alternate derivative calculation, they can provide it. The inclusion of finite diffs here is just a convenience for the lazy programmer. Since there are a variety of ways to get more accurate gradients, I don't want to include them all here (those are more properly in standalone libraries).
