### ISSUE TITLE
Fortran vs C question

### ISSUE THREAD

**Issue by neozhaoliang** [jacobwilliams/slsqp#18]
Hi: thanks for your excellent work. My question is not directly related with the algorithm, just want to ask  if C/C++ can replace the role of fortran in optimization? I see many code in this field are implemented in fortran, but considering fortran programs are usually quite difficult to read/maintain (and this language is publicly considered as obsolete), should there be a trend that new implementations of these algorithms be done with C/C++? Hope you could help me fix these questions, thanks!

**Comment by pirpyn** [comment]
Fortran is old, but not obsolete. Latest standard address coarray and parallel computation which is the concern of many people today. Also since 30 years Fortran has removed its limitations on source form which makes it as readable as C.
It has strong limitations which doesn't make it has multi-purpose as C/C++. 
But theses languages benefits from their standard library.  I'm sure a C program from 1975 is as cumbersome as Fortran 77 program.

**Comment by neozhaoliang** [comment]
I have seen some people saying that "you can make your native C/C++ code as fast as fortran with only a few more efforts". Is this true in your experience? Which features of fortran do you think make it more reasonable to implement an optimization algorithm in fortran rather than in C/C++? Or it's simply because fortran has lots of  scientific computating libraries so there no need to reinvent the wheels in C/C++?
